default: &default
  adapter: postgresql
  username: ada_volunteer_portal
  password: ENV['PG_SECRET']
  database: ada_volunteer_portal_development
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ada_volunteer_portal_development

test:
  <<: *default
  database: ada_volunteer_portal_test

production:
  <<: *default
  database: ada_volunteer_portal_production
